export type MaimaiPropertyCard = {
  title: string
  titleKey: string
  locationKey: string
  typeKey: string
  price: string
  area: string
  type: string
  location: string
  image: string
  href: string
  featureKey: 'maimai.properties.noFee' | 'maimai.properties.withFee'
  priceFormat?: 'oku'
}

export const maimaiPropertiesNoFee: MaimaiPropertyCard[] = [
  {
    title: '日興パレス南麻布 102・103号室',
    titleKey: 'maimai.properties.buildings.nikkoPalaceMinamiAzabu102103',
    locationKey: 'maimai.properties.locations.nikkoPalaceMinamiAzabu102103',
    typeKey: 'maimai.properties.types.shop',
    price: '13.2亿日元',
    priceFormat: 'oku',
    area: '301.50㎡',
    type: '店舗',
    location: '東京都港区南麻布',
    image: '/imgs/maimai/nikko-palace-minami-azabu-exterior.jpeg',
    href: '/maimai/nikko-palace-minami-azabu-102-103',
    featureKey: 'maimai.properties.noFee',
  },
  {
    title: 'ライオンズマンション東銀座2F',
    titleKey: 'maimai.properties.buildings.lionsHigashiginza2f',
    locationKey: 'maimai.properties.locations.lionsHigashiginza2f',
    typeKey: 'maimai.properties.types.shopOffice',
    price: '42,680万日元',
    area: '127.6㎡',
    type: '店舗・事務所',
    location: '東京都中央区築地',
    image: '/imgs/Lions Mansion Higashi-Ginza.jpeg',
    href: '/maimai/lions-higashiginza-2f',
    featureKey: 'maimai.properties.noFee',
  },
  {
    title: '新中野駅上プラザ310号室',
    titleKey: 'maimai.properties.buildings.shinNakano305',
    locationKey: 'maimai.properties.locations.shinNakano305',
    typeKey: 'maimai.properties.types.1r',
    price: '1,720万日元',
    area: '23.92㎡',
    type: '1R',
    location: '東京都中野区本町',
    image: '/imgs/maimai/shinnakanoekiue.jpeg',
    href: '/maimai/shin-nakano-ekijou-plaza-310',
    featureKey: 'maimai.properties.noFee',
  },
  {
    title: '新中野駅上プラザ304号室',
    titleKey: 'maimai.properties.buildings.shinNakano304',
    locationKey: 'maimai.properties.locations.shinNakano304',
    typeKey: 'maimai.properties.types.2ldk',
    price: '5,970万日元',
    area: '68.90㎡',
    type: '2LDK',
    location: '東京都中野区本町',
    image: '/imgs/maimai/shinnakanoekiue.jpeg',
    href: '/maimai/shin-nakano-ekijou-plaza-304',
    featureKey: 'maimai.properties.noFee',
  },
]

export const maimaiPropertiesWithFee: MaimaiPropertyCard[] = [
  {
    title: 'スカイコート向ヶ丘遊園 4F',
    titleKey: 'maimai.properties.buildings.skyCourtMukogaokaYuen4f',
    locationKey: 'maimai.properties.locations.skyCourtMukogaokaYuen4f',
    typeKey: 'maimai.properties.types.1k',
    price: '750万日元',
    area: '16.24㎡',
    type: '1K',
    location: '神奈川県川崎市多摩区登戸',
    image: '/imgs/maimai/sky-court-mukogaoka-yuen-exterior.jpg',
    href: '/maimai/sky-court-mukogaoka-yuen-4f',
    featureKey: 'maimai.properties.withFee',
  },
  {
    title: 'コマツエイト曲本 2F',
    titleKey: 'maimai.properties.buildings.komatsuEightMagumoto2f',
    locationKey: 'maimai.properties.locations.komatsuEightMagumoto2f',
    typeKey: 'maimai.properties.types.3ldk',
    price: '2,300万日元',
    area: '85.68㎡',
    type: '3LDK',
    location: '埼玉県さいたま市南区曲本',
    image: '/imgs/maimai/komatsu-eight-magumoto-exterior.jpg',
    href: '/maimai/komatsu-eight-magumoto-2f',
    featureKey: 'maimai.properties.withFee',
  },
  {
    title: 'グローリア初穂大塚 2F',
    titleKey: 'maimai.properties.buildings.gloriaHatsuhoOtsuka2f',
    locationKey: 'maimai.properties.locations.gloriaHatsuhoOtsuka2f',
    typeKey: 'maimai.properties.types.1r',
    price: '1,150万日元',
    area: '16.22㎡',
    type: '1R',
    location: '東京都豊島区上池袋',
    image: '/imgs/maimai/gloria-hatsuho-otsuka-exterior.jpg',
    href: '/maimai/gloria-hatsuho-otsuka-2f',
    featureKey: 'maimai.properties.withFee',
  },
  {
    title: 'エヴェナール西落合 4F',
    titleKey: 'maimai.properties.buildings.evenaNishiochiai4f',
    locationKey: 'maimai.properties.locations.evenaNishiochiai4f',
    typeKey: 'maimai.properties.types.1r',
    price: '1,000万日元',
    area: '16.52㎡',
    type: '1R',
    location: '東京都新宿区西落合',
    image: '/imgs/maimai/evena-nishiochiai-exterior.jpg',
    href: '/maimai/evena-nishiochiai-4f',
    featureKey: 'maimai.properties.withFee',
  },
  {
    title: 'ザ・パークハウス西新宿タワー60 52F',
    titleKey: 'maimai.properties.buildings.parkhouseNishiShinjukuTower6052f',
    locationKey: 'maimai.properties.locations.parkhouseNishiShinjukuTower6052f',
    typeKey: 'maimai.properties.types.3ldk',
    price: '24,461万日元',
    area: '89.86㎡',
    type: '3LDK',
    location: '東京都新宿区西新宿',
    image: '/imgs/maimai/parkhouse-nishi-shinjuku-tower60-exterior.jpg',
    href: '/maimai/parkhouse-nishi-shinjuku-tower60-52f',
    featureKey: 'maimai.properties.withFee',
  },
  {
    title: 'クラールハイト三宿Ⅱ',
    titleKey: 'maimai.properties.buildings.klarheitMishukuIi',
    locationKey: 'maimai.properties.locations.klarheitMishukuIi',
    typeKey: 'maimai.properties.types.commercialBuilding',
    price: '10.06亿日元',
    priceFormat: 'oku',
    area: '552.88㎡',
    type: '一棟店舗・事務所',
    location: '東京都世田谷区池尻',
    image: '/imgs/maimai/klarheit-mishuku-ii-exterior.jpg',
    href: '/maimai/klarheit-mishuku-ii',
    featureKey: 'maimai.properties.withFee',
  },
  {
    title: 'エクセリア世田谷上町 6F',
    titleKey: 'maimai.properties.buildings.exceriaSetagayaKamimachi6f',
    locationKey: 'maimai.properties.locations.exceriaSetagayaKamimachi6f',
    typeKey: 'maimai.properties.types.1k',
    price: '1,540万日元',
    area: '18.56㎡',
    type: '1K',
    location: '東京都世田谷区世田谷',
    image: '/imgs/maimai/exceria-setagaya-kamimachi-exterior.jpg',
    href: '/maimai/exceria-setagaya-kamimachi-6f',
    featureKey: 'maimai.properties.withFee',
  },
  {
    title: 'グレイス四谷 4F',
    titleKey: 'maimai.properties.buildings.graceYotsuya4f',
    locationKey: 'maimai.properties.locations.graceYotsuya4f',
    typeKey: 'maimai.properties.types.1r',
    price: '1,300万日元',
    area: '11.43㎡',
    type: '1R',
    location: '東京都新宿区舟町',
    image: '/imgs/maimai/grace-yotsuya-exterior.jpg',
    href: '/maimai/grace-yotsuya-4f',
    featureKey: 'maimai.properties.withFee',
  },
  {
    title: 'パティオ杉並 2F',
    titleKey: 'maimai.properties.buildings.patioSuginami2f',
    locationKey: 'maimai.properties.locations.patioSuginami2f',
    typeKey: 'maimai.properties.types.1r',
    price: '1,050万日元',
    area: '17.64㎡',
    type: '1R',
    location: '東京都杉並区堀ノ内',
    image: '/imgs/maimai/Patio Suginami 2F.jpeg',
    href: '/maimai/patio-suginami-203',
    featureKey: 'maimai.properties.withFee',
  },
  {
    title: "パレ・ドール相模原 8F",
    titleKey: 'maimai.properties.buildings.paleDorSagamihara8f',
    locationKey: 'maimai.properties.locations.paleDorSagamihara8f',
    typeKey: 'maimai.properties.types.1k',
    price: '420万日元',
    area: '16.29㎡',
    type: '1K',
    location: '神奈川県相模原市',
    image: "/imgs/maimai/palais-dor-sagamihara-exterior.jpeg",
    href: '/maimai/pale-dor-sagamihara-808',
    featureKey: 'maimai.properties.withFee',
  },
  {
    title: '日神パレス竹ノ塚 5F',
    titleKey: 'maimai.properties.buildings.nichishinPalaceTakenotsuka5f',
    locationKey: 'maimai.properties.locations.nichishinPalaceTakenotsuka5f',
    typeKey: 'maimai.properties.types.1r',
    price: '700万日元',
    area: '18.09㎡',
    type: '1R',
    location: '東京都足立区伊興',
    image: '/imgs/maimai/Nisshin Palace Takenotsuka 5f.jpeg',
    href: '/maimai/nichishin-palace-takenotsuka-509',
    featureKey: 'maimai.properties.withFee',
  },
  {
    title: 'セザール西高島平 2F',
    titleKey: 'maimai.properties.buildings.cesarTakashimadaira2f',
    locationKey: 'maimai.properties.locations.cesarTakashimadaira2f',
    typeKey: 'maimai.properties.types.1dk',
    price: '1,200万日元',
    area: '27.13㎡',
    type: '1DK',
    location: '東京都板橋区徳丸',
    image: '/imgs/Cesar Nishi Takashimadaira.jpeg',
    href: '/maimai/cesar-takashimadaira-206',
    featureKey: 'maimai.properties.withFee',
  },
  {
    title: '美和プラザ高井戸 9部屋バルク',
    titleKey: 'maimai.properties.buildings.miwaPlazaTakaido1f',
    locationKey: 'maimai.properties.locations.miwaPlazaTakaido1f',
    typeKey: 'maimai.properties.types.1r9units',
    price: '9,200万日元',
    area: '16.47㎡',
    type: '1R×9戸',
    location: '東京都杉並区上高井戸',
    image: '/imgs/maimai/Miwa Plaza Takaido 1.jpeg',
    href: '/maimai/miwa-plaza-takaido-101',
    featureKey: 'maimai.properties.withFee',
  },
  {
    title: 'LM西八王子第3 7F',
    titleKey: 'maimai.properties.buildings.lmNishihachioji3_707',
    locationKey: 'maimai.properties.locations.lmNishihachioji3_707',
    typeKey: 'maimai.properties.types.1k',
    price: '480万日元',
    area: '18.2㎡',
    type: '1K',
    location: '東京都八王子市八木町',
    image: '/imgs/maimai/Lions Mansion Nishi Hachioji 3-1.jpeg',
    href: '/maimai/lm-nishihachioji-3-707',
    featureKey: 'maimai.properties.withFee',
  },
  {
    title: 'スカイコート生田 2F',
    titleKey: 'maimai.properties.buildings.skyCourtIkuta2f',
    locationKey: 'maimai.properties.locations.skyCourtIkuta2f',
    typeKey: 'maimai.properties.types.1k',
    price: '430万日元',
    area: '约17㎡',
    type: '1K',
    location: '神奈川県川崎市多摩区',
    image: '/imgs/maimai/Sky Court Ikuta.jpeg',
    href: '/maimai/sky-court-ikuta-202',
    featureKey: 'maimai.properties.withFee',
  },
]

export const maimaiAllPropertyCards: MaimaiPropertyCard[] = [
  ...maimaiPropertiesNoFee,
  ...maimaiPropertiesWithFee,
]

